# Generated by Django 2.2 on 2019-08-28 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.TextField(default=None, null=True)),
                ('name2', models.TextField(default=None, null=True)),
                ('name3', models.TextField(default=None, null=True)),
                ('name4', models.TextField(default=None, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('count', models.IntegerField(default=0)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
