# Generated by Django 2.2 on 2019-08-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HkMn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name3',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name4',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
