# Generated by Django 2.2.5 on 2019-10-16 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HkMn', '0003_cafe_submissions_wifi'),
    ]

    operations = [
        migrations.CreateModel(
            name='judges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('tname', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HkMn.submissions')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
