# Generated by Django 2.2.5 on 2019-10-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HkMn', '0004_judges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.TextField(default='', null=True),
        ),
    ]
