# Generated by Django 2.2 on 2019-12-01 08:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HkMn', '0005_auto_20191019_0617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='judges',
            unique_together={('username', 'tname')},
        ),
    ]
