# Generated by Django 2.2 on 2019-12-01 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HkMn', '0006_auto_20191201_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judges',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
